jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: install deps
        run: make install
      - name: run linter
        run: make lint
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: install deps
        run: make install
      - name: run tests
        run: npm test
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: install deps
        run: make install
      - name: create build
        run: make build
